# Use the official PostgreSQL image from the Docker Hub
FROM postgres:13

# Set environment variables
ENV POSTGRES_DB=energydb
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password

# Expose the PostgreSQL port
EXPOSE 5432

# Set the default command for the container to run Postgres
CMD ["postgres"]
